services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI
      - MONGODB_DB_NAME
      - API_KEY
      - API_EMAIL
      - API_PASSWORD
      - JWT_SECRET_KEY
